* EULAbot
  I am writing EULAbot with the intention of gathering a large number of EULAs for analysis. It should, however, be simple and modular enough to be adapted easily for general use. 

** Some Definitions
   EULAbot has some specific meanings for a few fairly generic terms and this documentation will use the EULAbot specific meaning unless otherwise noted.

*** payload 
    a function that will be called for every page EULAbot crawls. EULAbot will call the payload function and pass the page text in as the first arguments. It is the job of the payload function to do whatever the Spider is there to do (look for EULAs, archive the whole page, ...)
             
*** Spider 
    One of the basic building blocks of EULAbot. A Spider is the object that maintains the crawl queue, handles the URLs on each page and runs the payload on each page. A Spider is restricted to one domain, is responsible for respecting that domain's robots.txt and respecting that domain's resources by following a reasonable timeout schedule.

** Testing
   The tests are written specifically to be run with the crawlThis test site. The test site can be found here. https://github.com/jessebmiller/crawlThis
   Just follow the directions in the README and the test suite should pass. Hopefully. 